### ISSUE TITLE
Names should be html unescaped

### ISSUE THREAD

**Issue by de-code** [elifesciences/data-pipeline-ejp-csv-deposit#5]
See [example in data-pipeline-ejp-to-json-converter](data-pipeline-ejp-to-json-converter). It should unescape names:

```python
import html

html.unescape(...)
```

That is important for name fields, like first name, last name etc.
However, we could probably apply that to any field.

Without it, for example:

```sql
SELECT reviewer_name FROM `elife-data-pipeline.prod.779_datascience_reviewer_info_all`
WHERE reviewer_person_id = '25647'
LIMIT 1
```

shows `L&#x00E1;szl&#x00F3; Csan&#x00E1;dy`

but should be: `László Csanády`

The correct value is shown for the following query (coming from XML - also html unescaped):
```sql
SELECT * FROM `elife-data-pipeline.prod.v_person_name` WHERE person_id = '25647'
```

/cc @lsh-0

**Comment by lsh-0** [comment]
no problems. 

is it a specific set of fields that should be targeted or *all* fields?

**Comment by lsh-0** [comment]
PR: https://github.com/elifesciences/data-pipeline-ejp-csv-deposit/pull/8

**Comment by de-code** [comment]
There will be a specific set of fields where that is required, generally name fields. It will never be useful on fields containing numbers or date/datetimes. But there doesn't seem to be any harm either. Therefore it might be best to just apply it to all (string) fields as in your PR.
