### ISSUE TITLE
Blank should be interpreted as NULL

### ISSUE THREAD

**Issue by de-code** [elifesciences/data-pipeline-ejp-csv-deposit#6]
More likely than not, a blank value represents a NULL value.
Currently I need to map it to NULL in views.
For example where Data Studio is meant to count values, it should correctly ignore NULLs (but it would count blanks).

I can't really think of an example where a value is meant to be genuinely blank.

/cc @lsh-0

**Comment by lsh-0** [comment]
We should transfer these two issues to the `issues` repo. There is a "Transfer issue" link to the bottom right that might help us out.

**Comment by lsh-0** [comment]
PR: https://github.com/elifesciences/data-pipeline-ejp-csv-deposit/pull/7

**Comment by de-code** [comment]
Why do you think we should transfer the issues? Don't we usually create issues against a single the repo if the change would be made in that repo and the issue itself doesn't contain private information?

BTW I think I don't have enough permissions for the transfer issue functionality on this repo.

**Comment by lsh-0** [comment]
I just thought all issues went into the great big `issues` repository, I don't mind either way, but just like the wiki, it's good to have a local clone to grep through on occasion
